#pragma once

#undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#undef CAPS_LOCK_LED_INDEX
#undef NUM_LOCK_LED_INDEX

#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_MULTISPLASH
#define RGB_MATRIX_DEFAULT_HUE 205
#define RGB_MATRIX_DEFAULT_SAT 212
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_DEFAULT_SPD 255

#define CAPS_LOCK_LED 61
#define NUM_LOCK_LED 37
